### ISSUE TITLE
issue with index building and search

### ISSUE THREAD

**Issue by devhero-tech** [swissup/module-search-mysql-legacy#10]
Hi, after instal and few tries of reindex on search. It looks like reindex can't create tables. Reindexing on 2000 products takes less than 1s ;)
 I've got error like this:

` SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalogsearch_fulltext_scope1' doesn't exist, query was: INSERT INTO `search_tmp_632cc6ff9ef500_89290962` SELECT `main_select`.`entity_id`, SUM(score) AS `relevance` FROM (SELECT DISTINCT  `eav_index`.`entity_id`, (((0)) * 1 + LEAST((MATCH (data_index) AGAINST ('age*' IN BOOLEAN MODE)), 1000000) * POW(2, search_weight)) AS `score` FROM `catalog_product_index_eav` AS `eav_index`
 INNER JOIN `catalogsearch_fulltext_scope1` AS `search_index` ON eav_index.entity_id = search_index.entity_id
 INNER JOIN `catalog_eav_attribute` AS `cea` ON search_index.attribute_id = cea.attribute_id
 INNER JOIN `cataloginventory_stock_status` AS `stock_index` ON stock_index.product_id = eav_index.entity_id AND `stock_index`.`website_id` = 0 AND `stock_index`.`stock_status` = 1 AND `stock_index`.`stock_id` = 1 WHERE (eav_index.store_id = '1') AND (`eav_index`.`attribute_id` = 99 AND `eav_index`.`value` in ('3', '4') AND `eav_index`.`store_id` = '1') AND (MATCH (data_index) AGAINST ('age*' IN BOOLEAN MODE))) AS `main_select` GROUP BY `entity_id`
Exception #1 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalogsearch_fulltext_scope1' doesn't exist, query was: INSERT INTO `search_tmp_632cc6ff9ef500_89290962` SELECT `main_select`.`entity_id`, SUM(score) AS `relevance` FROM (SELECT DISTINCT  `eav_index`.`entity_id`, (((0)) * 1 + LEAST((MATCH (data_index) AGAINST ('age*' IN BOOLEAN MODE)), 1000000) * POW(2, search_weight)) AS `score` FROM `catalog_product_index_eav` AS `eav_index`
 INNER JOIN `catalogsearch_fulltext_scope1` AS `search_index` ON eav_index.entity_id = search_index.entity_id
 INNER JOIN `catalog_eav_attribute` AS `cea` ON search_index.attribute_id = cea.attribute_id
 INNER JOIN `cataloginventory_stock_status` AS `stock_index` ON stock_index.product_id = eav_index.entity_id AND `stock_index`.`website_id` = 0 AND `stock_index`.`stock_status` = 1 AND `stock_index`.`stock_id` = 1 WHERE (eav_index.store_id = '1') AND (`eav_index`.`attribute_id` = 99 AND `eav_index`.`value` in ('3', '4') AND `eav_index`.`store_id` = '1') AND (MATCH (data_index) AGAINST ('age*' IN BOOLEAN MODE))) AS `main_select` GROUP BY `entity_id`
Exception #2 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.catalogsearch_fulltext_scope1' doesn't exist`

**Comment by 0m3r** [comment]
what is your Magento version? 
what are the config options?
```
bin/magento config:show catalog/search/enable_eav_indexer 
bin/magento config:show catalog/search/engine             
```
> I've got an error like this:

Where is your get/find the error? 
at some log file(s), frontend, indexing processes, etc.

**Comment by 0m3r** [comment]
related https://github.com/swissup/module-search-mysql-legacy/issues/9

**Comment by 0m3r** [comment]
Possible solution 

https://github.com/magento/magento2/issues/26520
https://github.com/magento/magento2/pull/26803/files

**Comment by 0m3r** [comment]
try this release 

https://github.com/swissup/module-search-mysql-legacy/releases/tag/1.1.4

```
composer update swissup/module-search-mysql-legacy
```
p.s. If doesn't help reopen the issue and give me more information plz
