### ISSUE TITLE
 unexpected token "match" Magento 2.4.5-p1 with PHP 8.1

### ISSUE THREAD

**Issue by ecoprince** [swissup/module-search-mysql-legacy#15]
I face below error during setup di compile

```syntax error, unexpected token "match", expecting identifier#0 /Sites/mysite/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Swissup\\SearchM...```

Magento 2.4.5-p1
Php 8.1

After further investigation found that class `Magento\Framework\Search\Request\Query\Filter` which is used in `\Swissup\SearchMysqlLegacy\SearchAdapter\Mysql\Mapper` is no longer available in Magento 2.4.5-p1.

Can you provide fix for this?

**Comment by 0m3r** [comment]
Are you using the last version of the code?

Something like that was fixed a couple of months ago

https://github.com/swissup/module-search-mysql-legacy/pull/7/files#diff-093a1e43a11122404c853506b7ca4f661e18dd4f6557ec3089cad8ceae34a606

**Comment by 0m3r** [comment]
> _After further investigation found that class `Magento\Framework\Search\Request\Query\Filter` which is used in `\Swissup\SearchMysqlLegacy\SearchAdapter\Mysql\Mapper` is no longer available in Magento 2.4.5-p1._

You mean that class `Magento\Framework\Search\Request\Query\Match` which is used in `\Swissup\SearchMysqlLegacy\SearchAdapter\Mysql\Mapper` is no longer available in Magento 2.4.5-p1

```php
use Magento\Framework\Search\Request\Query\Match as MatchQuery;
```
![Screenshot from 2023-01-19 18-46-23](https://user-images.githubusercontent.com/412612/213504651-18208193-b873-4800-88ac-e47409d146ec.png)

https://github.com/magento/magento2/commits/2.4-develop/lib/internal/Magento/Framework/Search/Request/Query/MatchQuery.php

https://github.com/magento/magento2/commit/b4b3c151031b3c129cb52709652408df1f508d74

**Comment by 0m3r** [comment]
I hope this patch will be enough to fix it 
```diff
diff --git a/SearchAdapter/Mysql/Mapper.php b/SearchAdapter/Mysql/Mapper.php
index 59b5ac3..137fa45 100644
--- a/SearchAdapter/Mysql/Mapper.php
+++ b/SearchAdapter/Mysql/Mapper.php
@@ -18,7 +18,6 @@ use Swissup\SearchMysqlLegacy\SearchAdapter\Mysql\Query\QueryContainerFactory;
 use Magento\Framework\Search\EntityMetadata;
 use Magento\Framework\Search\Request\Query\BoolExpression as BoolQuery;
 use Magento\Framework\Search\Request\Query\Filter as FilterQuery;
-use Magento\Framework\Search\Request\Query\Match as MatchQuery;
 use Magento\Framework\Search\Request\QueryInterface as RequestQueryInterface;
 use Magento\Framework\Search\RequestInterface;
 
@@ -220,7 +219,7 @@ class Mapper
     ) {
         switch ($query->getType()) {
             case RequestQueryInterface::TYPE_MATCH:
-                /** @var MatchQuery $query */
+                /** @var \Magento\Framework\Search\Request\Query\MatchQuery $query */
                 $select = $queryContainer->addMatchQuery(
                     $select,
                     $query,
```
@ecoprince please apply this patch and try to run `setup:di:compile`

**Comment by ecoprince** [comment]
@0m3r Fixed. Thanks!
