### ISSUE TITLE
Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by Detzler** [swissup/module-search-mysql-legacy#18]
Hello ✋

wanted to let you know:

`Deprecated Functionality: Creation of dynamic property Swissup\SearchMysqlLegacy\Model\Adapter\Mysql\Plugin\Aggregation\Category\DataProvider::$layer is deprecated in /vendor/swissup/module-search-mysql-legacy/Model/Adapter/Mysql/Plugin/Aggregation/Category/DataProvider.php on line 63`

**Comment by hostep** [comment]
Seems like it got fixed 3 days ago and released today in version 1.1.8 : https://github.com/swissup/module-search-mysql-legacy/commit/09477e13dfecaf1b6f8f68e0c920a913ff1e4b87

**Comment by Detzler** [comment]
@0m3r @hostep 

Nice thx.
