### ISSUE TITLE
Search results not showing proper in Search result page

### ISSUE THREAD

**Issue by niku911** [swissup/module-search-mysql-legacy#19]
Hi,

We facing some issues in Search result page or items not showing first as per the checked sorting by "Relevance" not working, https://prnt.sc/FpijNVEaxAX-
can you fix this to work properly?

**Comment by 0m3r** [comment]
Looks like it is not our module area of responsibility.
Try to use decision [here](https://magento.stackexchange.com/questions/195356/magento-2-1-x-search-by-relevance-does-not-work).
https://github.com/magento/magento2/issues/9066
