### ISSUE TITLE
CategoryFilter in Layered Navigation not working

### ISSUE THREAD

**Issue by Darkwolf81** [swissup/module-search-mysql-legacy#2]
Hello,

first of all, thank you for the module. That helped us very much after problems with ElasticSearch.
The only thing dont work with is the category filter. Everything else (Attribute Filtering) working fine. Switching to ES7 shows up the category filter again.
Is it possible to get this working?

Thank you very much,
Andreas

**Comment by 0m3r** [comment]
Hello,

Do you mean the category filter block is empty? 
I will check it out when I have free time
