### ISSUE TITLE
Indexing stopped working

### ISSUE THREAD

**Issue by roma84** [swissup/module-search-mysql-legacy#9]
I have installed the LMYSQL extension for Magento. 
Unfortunately, the indexing does not work anymore.

Magento is in version 2.4.3.
I have activated Legacy MySQL and Enable EAV Indexer (Yes) under Shops -> configuration -> catalog -> catalog search -> search engine.

**Comment by 0m3r** [comment]
> Unfortunately, the indexing does not work anymore.

What are you mean?

```
➜  magento245.local git:(master) ✗ bin/magento config:show catalog/search/enable_eav_indexer 
1
➜  magento245.local git:(master) ✗ bin/magento config:show catalog/search/engine             
lmysql

```

![Знімок екрана з 2022-09-13 11-30-33](https://user-images.githubusercontent.com/412612/189852516-41421b94-edc3-448d-a085-9ce65de0938d.png)
